### ISSUE TITLE
Make two new Pathfinders

### ISSUE THREAD

**Issue by elllie** [OOD-JOE/A4#2]

**Comment by janfic** [comment]
Here is a good wikipedia page for the Path Finding problem.
https://en.wikipedia.org/wiki/Maze_solving_algorithm

I would recommend Random Mouse Algorithm, Wall Flower, Trémaux's algorithm, or the ones under the Shortest Path section.

**Comment by mariaSheahata17** [comment]
Great! Thank you! After the DS midterm, I will send you which one I will
implement

**Comment by elllie** [comment]
I'm doing Wall Follower
